### ISSUE TITLE
Documentation - Details for setting up BigCommerce integration

### ISSUE THREAD

**Issue by amanjeetsingh** [MicrosoftDocs/dynamics-365-intelligent-order-management#1]
Hi 

Can you please show with examples on what steps must be taken after configuring a BigCommerce provider so that orders created in BigCommerce flow through to IOM? 

Example - what should be the Internal - External Mapping values? What other steps must be completed in addition to configuring BigCommerce (BC) provider before orders can flow through?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8ea1445-e45a-69e5-7473-7e058616159c
* Version Independent ID: c6a05d1e-2086-577a-8401-762ce91e83ea
* Content: [Set up BigCommerce provider](https://docs.microsoft.com/en-us/dynamics365/intelligent-order-management/set-up-bigcommerce-provider)
* Content Source: [topics/set-up-bigcommerce-provider.md](https://github.com/MicrosoftDocs/dynamics-365-intelligent-order-management-pr/blob/live/topics/set-up-bigcommerce-provider.md)
* Service: **dynamics-365-intelligent-order-management**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by josaw1** [comment]
Thanks for your feedback. @anvenkat, can you please review?
