### ISSUE TITLE
Cannot Save the Provider Definition Logic Definition record.

### ISSUE THREAD

**Issue by csbardella** [MicrosoftDocs/dynamics-365-intelligent-order-management#10]
Following the steps in the section, "Add provider definition logic definition to the provider definition".  Cannot save the record due to the following error message. Also attached is the error log file.

[ErrorDetails.txt](https://github.com/MicrosoftDocs/dynamics-365-intelligent-order-management/files/8980653/ErrorDetails.txt)

<img width="691" alt="image" src="https://user-images.githubusercontent.com/108139032/175666117-e832d245-5099-47de-938e-fd66955d6a60.png">

**Comment by josaw1** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
