### ISSUE TITLE
screenshot missing

### ISSUE THREAD

**Issue by TheMiao** [MicrosoftDocs/dynamics-365-intelligent-order-management#12]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eed9dfd9-50bb-bdfa-540f-bcdda75f75ed
* Version Independent ID: eed9dfd9-50bb-bdfa-540f-bcdda75f75ed
* Content: [Intelligent Order Management alerts](https://learn.microsoft.com/en-us/dynamics365/intelligent-order-management/alerts)
* Content Source: [topics/alerts.md](https://github.com/MicrosoftDocs/dynamics-365-intelligent-order-management-pr/blob/live/topics/alerts.md)
* Service: **dynamics-365-intelligent-order-management**
* GitHub Login: @derekkwanpm
* Microsoft Alias: **derekkwan**

**Comment by johnmichalak** [comment]
@TheMiao Thank you for letting us know. These images have been fixed and are now available.
