### ISSUE TITLE
Please specify where "Settings" is

### ISSUE THREAD

**Issue by linghonson** [MicrosoftDocs/dynamics-365-intelligent-order-management#15]
"Go to Settings > Advanced Settings." Where does Settings actually live in? Coming from another IOM doc page, I expect to find this "Settings" inside IOM but I don't think that is the case.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 92ee9d0d-4b63-20f7-9176-e9df52e2a800
* Version Independent ID: 4cca6c1e-3407-e42f-ca51-05d2aac23376
* Content: [Enable Bing Maps for your environment](https://learn.microsoft.com/en-us/dynamics365/intelligent-order-management/enable-bing-maps)
* Content Source: [topics/enable-bing-maps.md](https://github.com/MicrosoftDocs/dynamics-365-intelligent-order-management/blob/main/topics/enable-bing-maps.md)
* Service: **dynamics-365-intelligent-order-management**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by johnmichalak** [comment]
@linghornson Here is an image of the location of settings to help you find it: 
![image](https://github.com/MicrosoftDocs/dynamics-365-intelligent-order-management/assets/102557226/9321a81c-2849-4d99-9229-fd065ff57759)
