### ISSUE TITLE
Improper md syntax

### ISSUE THREAD

**Issue by fumi11** [MicrosoftDocs/dynamics-365-intelligent-order-management#17]
Improper md syntax. The lab steps is not rendered very well.

![image](https://github.com/MicrosoftDocs/dynamics-365-intelligent-order-management/assets/102130723/9249654c-89df-49be-bf3d-f1efcdc6c4e1)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 50fe20c4-49cc-b346-0bb4-c9c8b374510b
* Version Independent ID: 66bd2cda-910f-a01a-68c6-05b8ff3cf1bf
* Content: [Create fulfillment provider](https://learn.microsoft.com/en-us/dynamics365/intelligent-order-management/lab-create-fulfillment-provider)
* Content Source: [topics/lab-create-fulfillment-provider.md](https://github.com/MicrosoftDocs/dynamics-365-intelligent-order-management/blob/main/topics/lab-create-fulfillment-provider.md)
* Service: **dynamics-365-intelligent-order-management**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by johnmichalak** [comment]
Thank you, this has been fixed.
