### ISSUE TITLE
Source Object Name does not match

### ISSUE THREAD

**Issue by sasaeki** [MicrosoftDocs/dynamics-365-intelligent-order-management#2]
As far as I tested this quick start lab, Source Object Name in “Add transformation to the provider definition” section must be the same name as SourceObjectName of Parse JSON Content in “Create provider message handler” section.
The former is “IOMLabOrderIntakeProvider”, the latter is “IOMLab Order” in the current description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37cf6c99-4619-09f6-ad94-6d59dc574d33
* Version Independent ID: 12d529fe-2bfa-2999-daa1-fb637435ce9e
* Content: [Create intake provider](https://docs.microsoft.com/en-us/dynamics365/intelligent-order-management/lab-create-intake-provider)
* Content Source: [topics/lab-create-intake-provider.md](https://github.com/MicrosoftDocs/dynamics-365-intelligent-order-management-pr/blob/live/topics/lab-create-intake-provider.md)
* Service: **dynamics-365-intelligent-order-management**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by josaw1** [comment]
Thanks for the feedback. @raybennett-msft can you please review?

**Comment by raybennett-msft** [comment]
This looks to be resolved already, @josaw1 can you please close?
