### ISSUE TITLE
Section "Create Intelligent Order Management Data Transformer connection" is no longer required

### ISSUE THREAD

**Issue by cmossell** [MicrosoftDocs/dynamics-365-intelligent-order-management#24]
The section titled "Create Intelligent Order Management Data Transformer connection" is no longer applicable. It should be removed. All references to IOM Data Transformer connector should be removed from the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 37308970-09b7-a0ee-7dcc-5abbc12ce690
* Version Independent ID: 1a2c257a-56bf-fedb-d72c-e0cb3f25462d
* Content: [Create and configure connections](https://learn.microsoft.com/en-us/dynamics365/intelligent-order-management/lab-create-configure-connections)
* Content Source: [topics/lab-create-configure-connections.md](https://github.com/MicrosoftDocs/dynamics-365-intelligent-order-management/blob/main/topics/lab-create-configure-connections.md)
* Service: **dynamics-365-intelligent-order-management**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by johnmichalak** [comment]
This section has been removed.
