### ISSUE TITLE
Intelligent Order Management doc - Typo error in sub-heading 

### ISSUE THREAD

**Issue by amanjeetsingh** [MicrosoftDocs/dynamics-365-intelligent-order-management#3]
https://docs.microsoft.com/en-us/dynamics365/intelligent-order-management/lab-create-fulfillment-provider#add-pa-provider-definition-logic-definition-to-the-outlook-iomlabproviders-solution

![image](https://user-images.githubusercontent.com/7122931/153694277-3ccbab37-d397-4b72-a404-41cc03a9676f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50fe20c4-49cc-b346-0bb4-c9c8b374510b
* Version Independent ID: 66bd2cda-910f-a01a-68c6-05b8ff3cf1bf
* Content: [Create fulfillment provider](https://docs.microsoft.com/en-us/dynamics365/intelligent-order-management/lab-create-fulfillment-provider)
* Content Source: [topics/lab-create-fulfillment-provider.md](https://github.com/MicrosoftDocs/dynamics-365-intelligent-order-management-pr/blob/live/topics/lab-create-fulfillment-provider.md)
* Service: **dynamics-365-intelligent-order-management**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by josaw1** [comment]
Thank you for the feedback. I've corrected the typo and the article will be re-published today.
