### ISSUE TITLE
Logic Definition under Provider Definition too confusing  

### ISSUE THREAD

**Issue by fraga** [MicrosoftDocs/dynamics-365-intelligent-order-management#5]
[Add provider definition logic definition to the provider definition](https://docs.microsoft.com/en-us/dynamics365/intelligent-order-management/lab-create-intake-provider#add-provider-definition-logic-definition-to-the-provider-definition)

"Add provider definition logic definition to the provider definition"

Needs revision - found it to be too confusing, suggestion:

"Add Logic Definition to the Provider Definition" as the name implies we want to change the "Logic Definitions" from the "Provider Definition"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37cf6c99-4619-09f6-ad94-6d59dc574d33
* Version Independent ID: 12d529fe-2bfa-2999-daa1-fb637435ce9e
* Content: [Create intake provider](https://docs.microsoft.com/en-us/dynamics365/intelligent-order-management/lab-create-intake-provider)
* Content Source: [topics/lab-create-intake-provider.md](https://github.com/MicrosoftDocs/dynamics-365-intelligent-order-management-pr/blob/live/topics/lab-create-intake-provider.md)
* Service: **dynamics-365-intelligent-order-management**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by josaw1** [comment]
Thank you for your feedback. We will consider this in the next round of updates.
