### ISSUE TITLE
Missing step for activating the provider and the logic definition connections.

### ISSUE THREAD

**Issue by fraga** [MicrosoftDocs/dynamics-365-intelligent-order-management#6]
Missing step for activating the provider and the logic definition connections.

![image](https://user-images.githubusercontent.com/303538/155574173-e8ca2d39-6cff-4379-8028-45ebc5e7d4a5.png)

Connections must be enabled before the new auto generated flow in IOM connects to the dataverse or any other application

![image](https://user-images.githubusercontent.com/303538/155574535-3ec90ead-e5bc-462f-953e-4df1b8e0fbe6.png)

Error:

```Json
{
  "error": {
    "code": "0x80040265",
    "message": "Provider message handler is not available for power automate workflow id: f4624bfa-d594-ec11-b3fe-0022483c67de.. CorrelationId: 00ad2cea-f03c-4959-b1d8-9efc4b5e7449"
  }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37cf6c99-4619-09f6-ad94-6d59dc574d33
* Version Independent ID: 12d529fe-2bfa-2999-daa1-fb637435ce9e
* Content: [Create intake provider](https://docs.microsoft.com/en-us/dynamics365/intelligent-order-management/lab-create-intake-provider#add-provider-definition-logic-definition-to-the-provider-definition)
* Content Source: [topics/lab-create-intake-provider.md](https://github.com/MicrosoftDocs/dynamics-365-intelligent-order-management-pr/blob/live/topics/lab-create-intake-provider.md)
* Service: **dynamics-365-intelligent-order-management**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by josaw1** [comment]
Thanks for the feedback. @rinitha-reddy can you please review?

**Comment by raybennett-msft** [comment]
These steps are covered in another lab [Onboarding provider](https://github.com/MicrosoftDocs/dynamics-365-intelligent-order-management-pr.git)

@josaw1 feel free to close this issue
