### ISSUE TITLE
Title fix - Add pa provider definition logic definition to the Outlook IOMLabProviders solution

### ISSUE THREAD

**Issue by fraga** [MicrosoftDocs/dynamics-365-intelligent-order-management#7]
Fix title - "Add a provider definition logic definition to the Outlook IOMLabProviders solution"

https://docs.microsoft.com/en-us/dynamics365/intelligent-order-management/lab-create-fulfillment-provider#add-pa-provider-definition-logic-definition-to-the-outlook-iomlabproviders-solution

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50fe20c4-49cc-b346-0bb4-c9c8b374510b
* Version Independent ID: 66bd2cda-910f-a01a-68c6-05b8ff3cf1bf
* Content: [Create fulfillment provider](https://docs.microsoft.com/en-us/dynamics365/intelligent-order-management/lab-create-fulfillment-provider)
* Content Source: [topics/lab-create-fulfillment-provider.md](https://github.com/MicrosoftDocs/dynamics-365-intelligent-order-management-pr/blob/live/topics/lab-create-fulfillment-provider.md)
* Service: **dynamics-365-intelligent-order-management**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by josaw1** [comment]
Thank you for the feedback. I've corrected the typo and the article will be re-published today.
