### ISSUE TITLE
Create provider message handler - Parse JSON

### ISSUE THREAD

**Issue by cmossell** [MicrosoftDocs/dynamics-365-intelligent-order-management#8]
In section Create provider message handler:

- Step # 14 "Select New step and add "parse json"."
  - The step name has incorrect capitalization. It should read "Parse JSON".
- Step # 16 "Select Generate from sample and..."
  - The provided JSON text is the result, not the input. So it can either be directly pasted into the Schema field, or JSON text from step 15 can be used as input to **Generate from sample**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37cf6c99-4619-09f6-ad94-6d59dc574d33
* Version Independent ID: 12d529fe-2bfa-2999-daa1-fb637435ce9e
* Content: [Create intake provider](https://docs.microsoft.com/en-us/dynamics365/intelligent-order-management/lab-create-intake-provider)
* Content Source: [topics/lab-create-intake-provider.md](https://github.com/MicrosoftDocs/dynamics-365-intelligent-order-management-pr/blob/live/topics/lab-create-intake-provider.md)
* Service: **dynamics-365-intelligent-order-management**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by josaw1** [comment]
Thank you for your feedback. @raybennett-msft can you please review?

**Comment by raybennett-msft** [comment]
Created PR, please merge and resolve
