### ISSUE TITLE
URL query on create IOM connection is wrong

### ISSUE THREAD

**Issue by yokoshima-ms** [MicrosoftDocs/dynamics-365-intelligent-order-management#9]
Hi team,
I found that the url query which writen in below is wrong.
https://docs.microsoft.com/en-us/dynamics365/intelligent-order-management/lab-create-configure-connections
>If you don’t see the connector, append ?addConnectorHideKey=iomtransforme to the URL.

The correct query is ?addConnectorHideKey=iomtransforme**r**.

This typo is confusing and even a forum question was raised. Could you please correct it?
https://community.dynamics.com/365/dynamics-365-intelligent-order-management/f/dynamics-365-intelligent-order-management-forum/431266/i-cannot-find-the-iom-data-transformer-connector-in-power-automation

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 37308970-09b7-a0ee-7dcc-5abbc12ce690
* Version Independent ID: 1a2c257a-56bf-fedb-d72c-e0cb3f25462d
* Content: [接続の作成と構成](https://docs.microsoft.com/ja-jp/dynamics365/intelligent-order-management/lab-create-configure-connections)
* Content Source: [topics/lab-create-configure-connections.md](https://github.com/MicrosoftDocs/dynamics-365-intelligent-order-management-pr.ja-jp/blob/live/topics/lab-create-configure-connections.md)
* Service: **dynamics-365-intelligent-order-management**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by josaw1** [comment]
Thank you for your feedback. @raybennett-msft can you please review?

**Comment by raybennett-msft** [comment]
Submitted PR for fix.
